# Generated by Django 6.0.5 on 2026-07-13 10:47

import Accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Accounts.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor')], default='user', max_length=20),
        ),
    ]
